### PR TITLE
Remove requirement for a specific hostname

### LINKED ISSUE #52: Use wildcard DNS instead of static host address ?
The discussion in tuesday october the 22nd popped something in my mind, when @Mierdin mentioned asterisk wildcard...

Maybe this can be of use: http://xip.io/ can be used as a widlcard DNS service. I've seen it used in many cloud-related demos/tutorials.

Not exactly sure whether this would apply to the current situation, but maybe that helps working around the need to edit the hosts file.

### PR DESCRIPTION
**Pull request by Mierdin**
This removes the requirement for a specific hostname in the ingress definitions, and then also removes the logic to work with the `/etc/hosts` file, because it's not needed anymore.

Closes https://github.com/nre-learning/antidote-selfmedicate/issues/52

### CODE REVIEW

**Review by smk4664 — APPROVED** [review]
My only concern with this is that the IP could be changed by the user if they modify the vagrantfile.  But, I would assume if they know how to change the IP, they would know to use that IP.

**Comment by Mierdin** [comment]
@smk4664 You're right. Updated to retrieve `eth1` dyamically (and left a note on that portion of the Vagrantfile to let future us know it's being relied upon) in https://github.com/nre-learning/antidote-selfmedicate/pull/64/commits/537652309b1e3638314b178f6c1db236d3059c18

**Comment by smk4664** [comment]
@Mierdin Eth1 should work, but should we default it to localhost, then pass in the IP from the vagrantfile using antidote_config['vm_config']['private_network_ip']?  This way, the script could still work standalone?  I am also curious if Eth1 works if we change vm images.

**Comment by Mierdin** [comment]
I'm deciding to close this in favor of what I did in https://github.com/nre-learning/antidote-selfmedicate/pull/69/

I removed the hostname rules from the ingresses, but I still think there's value in having a hostname to point stuff to, particularly in the case of webssh which would otherwise need some sort of YAML templating nonsense to configure properly.

**Pull request closed without merging**
