### PR TITLE
Remove old selfmedicate (move to Vagrant) and add debug step

### LINKED ISSUE #37: Remove non-Vagrant selfmedicate
Need to make Vagrant the primary way for doing selfmedicate, with an option to run it directly if you want.

### PR DESCRIPTION
**Pull request by Mierdin**
It has become obvious that an automated tool to gather all of the relevant debug information for a selfmedicate environment is needed.

Once this is merged, we should be directing users to provide the output of this command for every issue they open, since we keep asking for this information.

Docs update in https://github.com/nre-learning/antidote/pull/61

# TODO

- [x] Deprecate old selfmedicate script and go with vagrant
- [x] Add control of k8s version (pin to 1.14.0 for now since that's what Antidote is running on)
- [x] finish adding rest of debug commands

Closes https://github.com/nre-learning/antidote-selfmedicate/issues/37

### CODE REVIEW

**Comment by cloudtoad** [comment]
What is the status of this?  If you give me some guidance, I can finish what was started (if it's not done yet).

**Comment by Mierdin** [comment]
It's mostly done. I have had a bunch of changes in staging for months and I just need to get them pushed. I'll do this ASAP - we can always add additional commands to them later.

**Comment by Mierdin** [comment]
Rather than add the logic to two scripts, I'm going to take the opportunity to deprecate the "old" selfmedicate in favor of the new Vagrant approach, which works great. I'll add the troubleshooting steps to that script.

**Review by cloudtoad — APPROVED** [review]
Looks good.  The troubleshooting bits will be extremely useful.

**Pull request merged**
